[tool.poetry]
name = "pick"
version = "2.5.0"
description = "Pick an option in the terminal with a simple GUI"
authors = ["wong2 <wonderfuly@gmail.com>", "AN Long <aisk1988@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/aisk/pick"
homepage = "https://github.com/aisk/pick"
keywords = ["terminal", "gui"]

[tool.poetry.dependencies]
python = ">=3.8"
windows-curses = {version = "^2.2.0", platform = "win32"}

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
mypy = "^1.4"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
